# Generated by Django 4.1 on 2022-09-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
